[config]
schemaVersion = "0.0.1"

[package]
namespace = "TritonSupreme"
name = "ExtraLandscapingTools"
versionNumber = "0.1.1"
description = "This mod aims to add features and improve existing ones for the game's landscaping tool."
websiteUrl = "https://github.com/AlphaGaming7780/ExtraLandscapingTools"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
# AuthorName-PackageName = "0.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods", "tools"]